___
# Atividade: <p> <center> Variáveis aleatórias discretas
___

## Aula 08

**Objetivo da aula:** Ao final desta aula, o aluno deve ser capaz de:
 * Descrever e aplicar propriedades de distribuições de probabilidades de variáveis aleatórias discretas; e
 * Compreender e aplicar propriedades de esperança e variância.


___
<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)


In [121]:
import numpy as np
import random
import pandas as pd

___
<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$ 50,00 a cada novo seguro que um corretor vende. <br>
A probabilidade de um cliente adquirir o seguro é de 0,20. <br> 
a) Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.<br>
b) Qual a probabilidade de um corretor ganhar apenas R\\$ 50,00?

**Resolução:** <p>
Primeiramente, vamos definir os seguintes eventos de acordo com enunciado:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i ou S_i^C$: o cliente $i$ não compra o seguro.

Ainda, pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

**item (a)**<br>
Lendo o enunciado, é fácil perceber que os possíveis valores que o corretor pode receber ao final de duas visitas são: 
**0 reais**, **50 reais** ou **100 reais**. <br>
Porém, qual a probabilidade que representa cada um desses valores acontecerem? Seria 1/3? <p>
A seguir, mostramos como construir a **distribuição de probabilidades desses possíveis valores que representam a comissão do corretor** ao final das duas visitas.

Listando todas as possíveis combinações de eventos de compra ou não compra do seguro de cada cliente, temos:

Cliente 1 | Cliente 2 | &nbsp; Probabilidade &nbsp; &nbsp;&nbsp; &nbsp; | Valor da comissão
:-------: | :-------: | :--------------------------:| :---:
$N_1$     | $N_2$     | $P(N_1)P(N_2|N_1)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2|N_1)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2|S_1)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2|S_1)$ = $0.04$ | 100

<br>

Agora, como estamos interessados em descrever os possíveis valores da comissão de um corretor e suas respectivas probabilidade, vamos definir uma letra que represente essa variável aleatória:

- $X$: valor da comissão do corretor ao final do dia, representando um valor aleatório;

em que $x$ = 0; 50; e 100 representando os possíveis valores que essa variável aleatória $X$ pode assumir.


**item (b)**<br>
Assim, o qual é o valor de $P(X=50)$?

Consultando a tabela construída acima, vemos que $P(X=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $X$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [122]:
# ESCREVA SEU CÓDIGO AQUI
P_N = 0.8
P_S = 0.2
P_NN = P_N*P_N
P_SN = 2*P_S*P_N
P_SS = P_S*P_S

esp = np.average([0,50,100], weights=[P_NN, P_SN, P_SS])
esp

20.0

In [123]:
var = np.average(([0,50,100]-esp)**2, weights=[P_NN, P_SN, P_SS])
var

800.0

___
## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- **Opção 1:** Defina $Y$ como a nova comissão que será a comissão atual mais um fixo de R\\$ 30,00;
- **Opção 2:** Defina $W$ como a nova comissão será o triplo da atual comissão.

<br>

A ideia aqui é fazer uma escolha de qual delas é melhor para aumentar o ganho de um corretor. 

Para isso, resolva os exercícios a seguir para auxiliá-lo nessa escolha.

<div id="ex2"></div>

### EXERCÍCIO 2

Construa a distribuição de probabilidade de $Y$ e de $W$ de acordo com cada uma das opções descritas acima.


Cliente 1 | Cliente 2 | &nbsp; Probabilidade &nbsp; &nbsp;&nbsp; &nbsp; | Y: Valor da comissão
:-------: | :-------: | :--------------------------:| :---:
$N_1$     | $N_2$     | $P(N_1)P(N_2|N_1)$ = $0.64$ | 30
$N_1$     | $S_2$     | $P(N_1)P(S_2|N_1)$ = $0.16$ | 80
$S_1$     | $N_2$     | $P(S_1)P(N_2|S_1)$ = $0.16$ | 80
$S_1$     | $S_2$     | $P(S_1)P(S_2|S_1)$ = $0.04$ | 130


Cliente 1 | Cliente 2 | &nbsp; Probabilidade &nbsp; &nbsp;&nbsp; &nbsp; | W: Valor da comissão
:-------: | :-------: | :--------------------------:| :---:
$N_1$     | $N_2$     | $P(N_1)P(N_2|N_1)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2|N_1)$ = $0.16$ | 150
$S_1$     | $N_2$     | $P(S_1)P(N_2|S_1)$ = $0.16$ | 150
$S_1$     | $S_2$     | $P(S_1)P(S_2|S_1)$ = $0.04$ | 300

<div id="ex3"></div>

### EXERCÍCIO 3

Considerando as respectivas distribuições de probabilidades, calcule o valor esperado e a variância para cada opção. 

In [124]:
# Y
esp_y = np.average([30,80,130], weights=[P_NN, P_SN, P_SS])
esp_y

50.0

In [125]:
var_y = np.average(([30,80,130]-esp_y)**2, weights=[P_NN, P_SN, P_SS])
var_y

800.0

In [126]:
# W
esp_w = np.average([0,150,300], weights=[P_NN, P_SN, P_SS])
esp_w

59.99999999999999

In [127]:
var_w = np.average(([0,150,300]-esp_w)**2, weights=[P_NN, P_SN, P_SS])
var_w

7199.999999999998

<div id="ex4"></div>

### EXERCÍCIO 4

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 50.0 reais ; 60.0 reais*

In [128]:
# ESCREVA SEU CÓDIGO AQUI
esp_y2 = esp+30
esp_y2

50.0

In [129]:
esp_w2 = 3*esp
esp_w2

60.0

<div id="ex5"></div>

### EXERCÍCIO 5

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 7200.0 reais^2*

In [130]:
# ESCREVA SEU CÓDIGO AQUI
var_y2 = var
var_y2

800.0

In [131]:
var_w2 = 3**2*var
var_w2

7200.0

<div id="ex6"></div>

### EXERCÍCIO 6

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)